from crewai import Task
from tools import google_search_tool
from agents import introduction_agent, literature_review_agent, methodology_agent, implementation_agent, results_analytics_agent, reference_agent,proof_agent
# This file contains task definitions for each research bot agent
# Each task corresponds to an agent's role in the research workflow

introduction_task = Task(
    description=("""
    Create a compelling introduction for a research paper on the topic: {topic}. 
    The introduction should set the context, highlight the significance of the research, 
    and clearly state the objectives and contributions of the study.
    """),
    expected_output="A well-structured introduction paragraph for the topic: {topic}, formatted as markdown.",
    tools=[google_search_tool],
    agent=introduction_agent,
    async_execution=False
)


literature_review_task = Task(
    description=("""
    Conduct a comprehensive literature review on the topic: {topic}. 
    Summarize key findings, identify gaps in the existing research, and provide a critical analysis 
    of methodologies used in the literature. The review should be well-organized and insightful.
    """),
    expected_output="A detailed literature review on the topic: {topic}, formatted as markdown.",
    tools=[google_search_tool],
    agent=literature_review_agent,
    async_execution=False
)


methodology_task = Task(
    description=("""
    Develop a clear and replicable research methodology for the topic: {topic}. 
    Describe the research design, data collection methods, and analysis techniques. 
    Justify the chosen methods and address any potential limitations.
    """),
    expected_output="A comprehensive methodology section for the topic: {topic}, formatted as markdown.",
    tools=[google_search_tool],
    agent=methodology_agent,
    async_execution=False
)


implementation_task = Task(
    description=("""
    Outline the implementation plan for the research on the topic: {topic}. 
    Detail the steps, resources, and timelines required to execute the research effectively. 
    Include any potential challenges and how they will be addressed.
    """),
    expected_output="A structured implementation plan for the topic: {topic}, formatted as markdown.",
    tools=[google_search_tool],
    agent=implementation_agent,
    async_execution=False
)


results_analytics_task = Task(
    description=("""
    Analyze the results obtained from the research on the topic: {topic}. 
    Present the findings clearly, identify patterns, and interpret the significance of the results. 
    Visualizations may be included to enhance understanding.
    """),
    expected_output="A results analysis report for the topic: {topic}, formatted as markdown.",
    tools=[google_search_tool],
    agent=results_analytics_agent,
    async_execution=False
)


reference_task = Task(
    description=("""
    Compile and format all references used in the research on the topic: {topic}. 
    Ensure that all citations are accurate and adhere to academic standards. 
    Provide additional sources for further reading on the topic.
    """),
    expected_output="A formatted reference list for the topic: {topic}, including additional sources for further reading.",
    tools=[],
    agent=reference_agent,
    async_execution=False
)


proof_read_task = Task(
    description=("""
    Finalize insightful content on the topic: {topic} generated by all research agents. 
    Focus on accuracy, structure, clarity, and readability. Correct any mistakes and ensure the content is easy to understand. 
    Properly cite all information sources and provide three additional references for further study. 
    The final output should be engaging, positive, and polished for stakeholder review.
    """),
    expected_output="A comprehensive and polished article on the topic: {topic}, formatted as markdown with all relevant sources included.",
    tools=[google_search_tool],
    agent=proof_agent,
    async_execution=False,
    output_file="final_report.md"
)